/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Analysis: () => import('#controllers/analysis_controller'),
  Me: () => import('#controllers/me_controller'),
}
