import { BaseSeeder } from '@adonisjs/lucid/seeders'
import db from '@adonisjs/lucid/services/db'

export default class PairsSeeder extends BaseSeeder {
  async run() {
    await db.table('pairs').multiInsert([
      // Majors
      {
        symbol: 'EUR/USD',
        massive_ticker: 'C:EURUSD',
        base_currency: 'EUR',
        quote_currency: 'USD',
        pip_size: 0.0001,
        pip_value_usd: 10.0,
        spread_avg: 1.2,
        category: 'major',
        sessions: JSON.stringify(['london', 'new_york']),
        is_active: true,
        created_at: new Date(),
      },
      {
        symbol: 'GBP/USD',
        massive_ticker: 'C:GBPUSD',
        base_currency: 'GBP',
        quote_currency: 'USD',
        pip_size: 0.0001,
        pip_value_usd: 10.0,
        spread_avg: 1.5,
        category: 'major',
        sessions: JSON.stringify(['london', 'new_york']),
        is_active: true,
        created_at: new Date(),
      },
      {
        symbol: 'USD/JPY',
        massive_ticker: 'C:USDJPY',
        base_currency: 'USD',
        quote_currency: 'JPY',
        pip_size: 0.01,
        pip_value_usd: 6.67,
        spread_avg: 1.3,
        category: 'major',
        sessions: JSON.stringify(['tokyo', 'new_york']),
        is_active: true,
        created_at: new Date(),
      },
      {
        symbol: 'USD/CHF',
        massive_ticker: 'C:USDCHF',
        base_currency: 'USD',
        quote_currency: 'CHF',
        pip_size: 0.0001,
        pip_value_usd: 10.0,
        spread_avg: 1.5,
        category: 'major',
        sessions: JSON.stringify(['london', 'new_york']),
        is_active: true,
        created_at: new Date(),
      },
      {
        symbol: 'AUD/USD',
        massive_ticker: 'C:AUDUSD',
        base_currency: 'AUD',
        quote_currency: 'USD',
        pip_size: 0.0001,
        pip_value_usd: 10.0,
        spread_avg: 1.4,
        category: 'major',
        sessions: JSON.stringify(['tokyo', 'new_york']),
        is_active: true,
        created_at: new Date(),
      },
      {
        symbol: 'USD/CAD',
        massive_ticker: 'C:USDCAD',
        base_currency: 'USD',
        quote_currency: 'CAD',
        pip_size: 0.0001,
        pip_value_usd: 7.35,
        spread_avg: 1.6,
        category: 'major',
        sessions: JSON.stringify(['new_york']),
        is_active: true,
        created_at: new Date(),
      },
      {
        symbol: 'NZD/USD',
        massive_ticker: 'C:NZDUSD',
        base_currency: 'NZD',
        quote_currency: 'USD',
        pip_size: 0.0001,
        pip_value_usd: 10.0,
        spread_avg: 1.8,
        category: 'major',
        sessions: JSON.stringify(['tokyo', 'new_york']),
        is_active: true,
        created_at: new Date(),
      },
      // Minors / Crosses
      {
        symbol: 'EUR/GBP',
        massive_ticker: 'C:EURGBP',
        base_currency: 'EUR',
        quote_currency: 'GBP',
        pip_size: 0.0001,
        pip_value_usd: 12.5,
        spread_avg: 1.8,
        category: 'minor',
        sessions: JSON.stringify(['london']),
        is_active: true,
        created_at: new Date(),
      },
      {
        symbol: 'EUR/JPY',
        massive_ticker: 'C:EURJPY',
        base_currency: 'EUR',
        quote_currency: 'JPY',
        pip_size: 0.01,
        pip_value_usd: 6.67,
        spread_avg: 2.0,
        category: 'minor',
        sessions: JSON.stringify(['london', 'tokyo']),
        is_active: true,
        created_at: new Date(),
      },
      {
        symbol: 'GBP/JPY',
        massive_ticker: 'C:GBPJPY',
        base_currency: 'GBP',
        quote_currency: 'JPY',
        pip_size: 0.01,
        pip_value_usd: 6.67,
        spread_avg: 2.8,
        category: 'minor',
        sessions: JSON.stringify(['london', 'tokyo']),
        is_active: true,
        created_at: new Date(),
      },
    ])
  }
}
