/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AlertSchema extends BaseModel {
  static $columns = ['body', 'channel', 'createdAt', 'id', 'isRead', 'readAt', 'sentAt', 'signalId', 'title', 'userId'] as const
  $columns = AlertSchema.$columns
  @column()
  declare body: string | null
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRead: boolean
  @column.dateTime()
  declare readAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime
  @column()
  declare signalId: string | null
  @column()
  declare title: string
  @column()
  declare userId: string
}

export class AnalysisSchema extends BaseModel {
  static $columns = ['aiReasoning', 'createdAt', 'durationMs', 'executedAt', 'id', 'marketBias', 'newsSentiment', 'newsSummary', 'pairId', 'score', 'status', 'summary', 'timeframePrimary', 'timeframesAnalyzed', 'trendStrength', 'triggerType', 'userId'] as const
  $columns = AnalysisSchema.$columns
  @column()
  declare aiReasoning: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column.dateTime()
  declare executedAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare marketBias: string | null
  @column()
  declare newsSentiment: string | null
  @column()
  declare newsSummary: string | null
  @column()
  declare pairId: number
  @column()
  declare score: number | null
  @column()
  declare status: string
  @column()
  declare summary: string | null
  @column()
  declare timeframePrimary: string
  @column()
  declare timeframesAnalyzed: any
  @column()
  declare trendStrength: number | null
  @column()
  declare triggerType: string
  @column()
  declare userId: string | null
}

export class AnalysisIndicatorSchema extends BaseModel {
  static $columns = ['analysisId', 'createdAt', 'extraValues', 'id', 'indicatorName', 'interpretation', 'timeframe', 'value'] as const
  $columns = AnalysisIndicatorSchema.$columns
  @column()
  declare analysisId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare extraValues: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare indicatorName: string
  @column()
  declare interpretation: string | null
  @column()
  declare timeframe: string
  @column()
  declare value: string | null
}

export class AnalysisJobSchema extends BaseModel {
  static $columns = ['createdAt', 'errorMessage', 'finishedAt', 'id', 'pairsAnalyzed', 'session', 'signalsGenerated', 'startedAt', 'status'] as const
  $columns = AnalysisJobSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pairsAnalyzed: any
  @column()
  declare session: string
  @column()
  declare signalsGenerated: number
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
}

export class EconomicEventSchema extends BaseModel {
  static $columns = ['actual', 'createdAt', 'currency', 'eventAt', 'forecast', 'id', 'impact', 'previous', 'title'] as const
  $columns = EconomicEventSchema.$columns
  @column()
  declare actual: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column.dateTime()
  declare eventAt: DateTime
  @column()
  declare forecast: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare impact: string
  @column()
  declare previous: string | null
  @column()
  declare title: string
}

export class PairSchema extends BaseModel {
  static $columns = ['baseCurrency', 'category', 'createdAt', 'id', 'isActive', 'massiveTicker', 'pipSize', 'pipValueUsd', 'quoteCurrency', 'sessions', 'spreadAvg', 'symbol'] as const
  $columns = PairSchema.$columns
  @column()
  declare baseCurrency: string
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare massiveTicker: string
  @column()
  declare pipSize: string
  @column()
  declare pipValueUsd: string
  @column()
  declare quoteCurrency: string
  @column()
  declare sessions: any
  @column()
  declare spreadAvg: string
  @column()
  declare symbol: string
}

export class SignalConfluenceSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'factorType', 'id', 'signalId', 'timeframe', 'weight'] as const
  $columns = SignalConfluenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare factorType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare signalId: string
  @column()
  declare timeframe: string
  @column()
  declare weight: string
}

export class SignalSchema extends BaseModel {
  static $columns = ['activatedAt', 'analysisId', 'classification', 'closePrice', 'closedAt', 'confluenceCount', 'createdAt', 'direction', 'entryPrice', 'expiresAt', 'id', 'invalidationLevel', 'lotSize', 'notes', 'pairId', 'pipsAtRisk', 'pipsToTp1', 'pipsToTp2', 'pipsToTp3', 'pnlMoney', 'pnlPips', 'riskPercent', 'riskReward', 'score', 'signalType', 'status', 'stopLoss', 'takeProfit1', 'takeProfit2', 'takeProfit3', 'timeframeAlignment', 'updatedAt', 'userId'] as const
  $columns = SignalSchema.$columns
  @column.dateTime()
  declare activatedAt: DateTime | null
  @column()
  declare analysisId: string | null
  @column()
  declare classification: string
  @column()
  declare closePrice: string | null
  @column.dateTime()
  declare closedAt: DateTime | null
  @column()
  declare confluenceCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare direction: string
  @column()
  declare entryPrice: string
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invalidationLevel: string | null
  @column()
  declare lotSize: string
  @column()
  declare notes: string | null
  @column()
  declare pairId: number
  @column()
  declare pipsAtRisk: string
  @column()
  declare pipsToTp1: string
  @column()
  declare pipsToTp2: string | null
  @column()
  declare pipsToTp3: string | null
  @column()
  declare pnlMoney: string | null
  @column()
  declare pnlPips: string | null
  @column()
  declare riskPercent: string
  @column()
  declare riskReward: string
  @column()
  declare score: number
  @column()
  declare signalType: string
  @column()
  declare status: string
  @column()
  declare stopLoss: string
  @column()
  declare takeProfit1: string
  @column()
  declare takeProfit2: string | null
  @column()
  declare takeProfit3: string | null
  @column()
  declare timeframeAlignment: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class TradePartialSchema extends BaseModel {
  static $columns = ['closePrice', 'closedAt', 'id', 'level', 'percentage', 'pnlMoney', 'pnlPips', 'tradeId'] as const
  $columns = TradePartialSchema.$columns
  @column()
  declare closePrice: string
  @column.dateTime()
  declare closedAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: string
  @column()
  declare percentage: string
  @column()
  declare pnlMoney: string
  @column()
  declare pnlPips: string
  @column()
  declare tradeId: string
}

export class TradeSchema extends BaseModel {
  static $columns = ['brokerOrderId', 'closePrice', 'closeReason', 'closedAt', 'commission', 'createdAt', 'currentSl', 'direction', 'entryPrice', 'executionType', 'id', 'lotSize', 'openedAt', 'pairId', 'pnlMoney', 'pnlPips', 'riskPercent', 'signalId', 'status', 'stopLoss', 'swap', 'takeProfit1', 'takeProfit2', 'takeProfit3', 'updatedAt', 'userId'] as const
  $columns = TradeSchema.$columns
  @column()
  declare brokerOrderId: string | null
  @column()
  declare closePrice: string | null
  @column()
  declare closeReason: string | null
  @column.dateTime()
  declare closedAt: DateTime | null
  @column()
  declare commission: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentSl: string
  @column()
  declare direction: string
  @column()
  declare entryPrice: string
  @column()
  declare executionType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lotSize: string
  @column.dateTime()
  declare openedAt: DateTime
  @column()
  declare pairId: number
  @column()
  declare pnlMoney: string | null
  @column()
  declare pnlPips: string | null
  @column()
  declare riskPercent: string
  @column()
  declare signalId: string | null
  @column()
  declare status: string
  @column()
  declare stopLoss: string
  @column()
  declare swap: string | null
  @column()
  declare takeProfit1: string
  @column()
  declare takeProfit2: string | null
  @column()
  declare takeProfit3: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSettingSchema extends BaseModel {
  static $columns = ['alertChannels', 'brokerConfig', 'createdAt', 'id', 'maxDailyDrawdown', 'maxOpenPositions', 'maxRiskPerTrade', 'maxWeeklyDrawdown', 'minSignalClass', 'minSignalScore', 'preferredPairs', 'preferredSessions', 'timezone', 'updatedAt', 'userId'] as const
  $columns = UserSettingSchema.$columns
  @column()
  declare alertChannels: any
  @column()
  declare brokerConfig: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxDailyDrawdown: string
  @column()
  declare maxOpenPositions: number
  @column()
  declare maxRiskPerTrade: string
  @column()
  declare maxWeeklyDrawdown: string
  @column()
  declare minSignalClass: string
  @column()
  declare minSignalScore: number
  @column()
  declare preferredPairs: any
  @column()
  declare preferredSessions: any
  @column()
  declare timezone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['accountBalance', 'accountCurrency', 'avatarUrl', 'cognitoSub', 'createdAt', 'email', 'fullName', 'id', 'isActive', 'lastLoginAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare accountBalance: string
  @column()
  declare accountCurrency: string
  @column()
  declare avatarUrl: string | null
  @column()
  declare cognitoSub: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
