/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BrokerConfigSchema extends BaseModel {
  static $columns = ['accountType', 'brokerName', 'createdAt', 'id', 'isActive', 'lastConnectedAt', 'mt5Login', 'mt5PasswordEncrypted', 'mt5Server', 'symbolSuffix', 'updatedAt', 'userId'] as const
  $columns = BrokerConfigSchema.$columns
  @column()
  declare accountType: string
  @column()
  declare brokerName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastConnectedAt: DateTime | null
  @column()
  declare mt5Login: number
  @column()
  declare mt5PasswordEncrypted: string
  @column()
  declare mt5Server: string
  @column()
  declare symbolSuffix: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class DailySummarySchema extends BaseModel {
  static $columns = ['balanceEnd', 'balanceStart', 'bestTradeUsd', 'createdAt', 'date', 'id', 'maxDrawdownUsd', 'realizedPnl', 'targetReached', 'targetUsd', 'tradesLost', 'tradesTotal', 'tradesWon', 'userId', 'winRate', 'worstTradeUsd'] as const
  $columns = DailySummarySchema.$columns
  @column()
  declare balanceEnd: string | null
  @column()
  declare balanceStart: string | null
  @column()
  declare bestTradeUsd: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maxDrawdownUsd: string | null
  @column()
  declare realizedPnl: string | null
  @column()
  declare targetReached: boolean
  @column()
  declare targetUsd: string | null
  @column()
  declare tradesLost: number
  @column()
  declare tradesTotal: number
  @column()
  declare tradesWon: number
  @column()
  declare userId: string
  @column()
  declare winRate: string | null
  @column()
  declare worstTradeUsd: string | null
}

export class HourlyLogSchema extends BaseModel {
  static $columns = ['balanceUsd', 'createdAt', 'cumulativePnlToday', 'decisionSummary', 'equityUsd', 'id', 'marketContext', 'openPositions', 'pnlThisHour', 'session', 'symbolsAnalyzed', 'targetProgressPct', 'timestamp', 'tradesClosed', 'tradesOpened', 'tradesSkipped', 'userId', 'utcHour'] as const
  $columns = HourlyLogSchema.$columns
  @column()
  declare balanceUsd: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cumulativePnlToday: string | null
  @column()
  declare decisionSummary: string | null
  @column()
  declare equityUsd: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare marketContext: string | null
  @column()
  declare openPositions: number
  @column()
  declare pnlThisHour: string | null
  @column()
  declare session: string | null
  @column()
  declare symbolsAnalyzed: any | null
  @column()
  declare targetProgressPct: string | null
  @column.dateTime()
  declare timestamp: DateTime
  @column()
  declare tradesClosed: number
  @column()
  declare tradesOpened: number
  @column()
  declare tradesSkipped: number
  @column()
  declare userId: string
  @column()
  declare utcHour: number
}

export class PairSchema extends BaseModel {
  static $columns = ['baseCurrency', 'category', 'createdAt', 'id', 'isActive', 'pipSize', 'pipValueUsd', 'quoteCurrency', 'sessions', 'spreadAvg', 'symbol'] as const
  $columns = PairSchema.$columns
  @column()
  declare baseCurrency: string
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare pipSize: string
  @column()
  declare pipValueUsd: string
  @column()
  declare quoteCurrency: string
  @column()
  declare sessions: any
  @column()
  declare spreadAvg: string
  @column()
  declare symbol: string
}

export class TradeSchema extends BaseModel {
  static $columns = ['closeReason', 'closedAt', 'comment', 'commission', 'createdAt', 'entryPrice', 'exitPrice', 'holdingMinutes', 'hourlyLogId', 'id', 'lotSize', 'openedAt', 'pairId', 'pnlPips', 'pnlUsd', 'riskUsd', 'rrAchieved', 'rrRatio', 'side', 'slPips', 'slPrice', 'status', 'swap', 'ticket', 'tpPips', 'tpPrice', 'updatedAt', 'userId'] as const
  $columns = TradeSchema.$columns
  @column()
  declare closeReason: string | null
  @column.dateTime()
  declare closedAt: DateTime | null
  @column()
  declare comment: string | null
  @column()
  declare commission: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entryPrice: string
  @column()
  declare exitPrice: string | null
  @column()
  declare holdingMinutes: string | null
  @column()
  declare hourlyLogId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lotSize: string
  @column.dateTime()
  declare openedAt: DateTime
  @column()
  declare pairId: number
  @column()
  declare pnlPips: string | null
  @column()
  declare pnlUsd: string | null
  @column()
  declare riskUsd: string
  @column()
  declare rrAchieved: string | null
  @column()
  declare rrRatio: string
  @column()
  declare side: string
  @column()
  declare slPips: string
  @column()
  declare slPrice: string
  @column()
  declare status: string
  @column()
  declare swap: string | null
  @column()
  declare ticket: bigint | number | null
  @column()
  declare tpPips: string
  @column()
  declare tpPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class TradingSettingSchema extends BaseModel {
  static $columns = ['allowedPairs', 'autoTradingEnabled', 'createdAt', 'dailyTargetPct', 'defaultLotSize', 'id', 'killSwitch', 'maxConsecutiveLosses', 'maxDailyLossPct', 'maxDrawdownPct', 'maxLotSize', 'maxOpenPositions', 'maxRiskPerTradePct', 'maxSpreadPips', 'maxTradeDurationMinutes', 'minAdxEntry', 'minAlignmentScore', 'minRrRatio', 'newsBufferMinutes', 'reduceLotAtPct', 'tradingEndUtc', 'tradingStartUtc', 'updatedAt', 'userId'] as const
  $columns = TradingSettingSchema.$columns
  @column()
  declare allowedPairs: any
  @column()
  declare autoTradingEnabled: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dailyTargetPct: string
  @column()
  declare defaultLotSize: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare killSwitch: boolean
  @column()
  declare maxConsecutiveLosses: number
  @column()
  declare maxDailyLossPct: string
  @column()
  declare maxDrawdownPct: string
  @column()
  declare maxLotSize: string
  @column()
  declare maxOpenPositions: number
  @column()
  declare maxRiskPerTradePct: string
  @column()
  declare maxSpreadPips: string
  @column()
  declare maxTradeDurationMinutes: number
  @column()
  declare minAdxEntry: number
  @column()
  declare minAlignmentScore: number
  @column()
  declare minRrRatio: string
  @column()
  declare newsBufferMinutes: number
  @column()
  declare reduceLotAtPct: number
  @column()
  declare tradingEndUtc: string
  @column()
  declare tradingStartUtc: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['accountCurrency', 'cognitoSub', 'createdAt', 'email', 'fullName', 'id', 'isActive', 'lastLoginAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare accountCurrency: string
  @column()
  declare cognitoSub: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
